language: php
sudo: required
dist: trusty
install:
  - . $HOME/.nvm/nvm.sh
   - nvm install stable
   - nvm use stable
env:
  global:

  matrix:

php:
  - 7.0

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

addons:
  chrome: stable

cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true

before_script:
- # Get ChromeDriver for headless mode
- wget "https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
- unzip "chromedriver_linux64.zip"
- mkdir -p /usr/local/bin
- sudo cp -a chromedriver /usr/local/bin
- sudo chmod +x /usr/local/bin/chromedriver

- npm install

script:
- composer install --prefer-dist
- composer update
- cd tests
- mv acceptance.suite.dist.yml acceptance.suite.yml
- cd ..
- vendor/bin/codecept bootstrap
- vendor/bin/robo run:test

